# Generated by Django 5.2.14 on 2026-09-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0026_merge_20260825_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='funcao_gestao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='loja_gestao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='status_gestao',
        ),
    ]
