"""Configurações e constantes do Fechamento de Faltas Atacadão e Assaí.

Todas as parametrizações operacionais e regras parametrizáveis são centralizadas aqui,
evitando condicionais hardcoded espalhadas no código.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Set


# Termos/padrões de lojas que devem ser excluídas da apuração Atacadão/Assaí
EXCLUDED_STORE_PATTERNS: List[str] = [
    'lapdarte',
    'aps',
    'dia',
    'fort',
    'protege',
]

# Normalização de nomes longos de lojas (>50 caracteres no GeoVictoria)
STORE_NAME_MAPPING: Dict[str, str] = {
    'Atacadão São José dos Campos Shopping - Lj 813': 'Atacadão SJC Shopping - Lj 813',
    'Fort Atacadista - São Francisco do Sul - LJ 395': 'Fort São Francisco do Sul',
    'Vinicius - Atacadão São José dos Campos Shopping - Lj 813': 'Atacadão SJC Shopping - Lj 813',
}

# Permissões do Controle de Ponto que representam Outras Folgas
OUTRAS_FOLGAS_PERMISSIONS: Set[str] = {
    'DOMINGO DO MÊS',
    'Folga Compensatória',
    'Folga Compensatória ',
    'Folga Feriado',
    'Troca de Folga',
    'Folga de troca de horário',
    'Folga remunerada',
    'Compensação Banco de Horas',
    'Feriado',
    'Descanso de viagem',
}

# Permissões que representam afastamentos ou licenças
AFASTAMENTOS_PERMISSIONS: Set[str] = {
    'Férias',
    'Afastamento Previdenciário',
    'Licença Maternidade',
    'Auxílio Doença',
    'Licença Casamento',
    'Licença Luto',
    'Serviço Militar',
}

# Limite padrão de equivalência de Horas Extras em Diária (0 = desativado)
DEFAULT_HEC_EQUIVALENCIA_MINUTOS: int = 0


@dataclass
class SharedStoreGroup:
    """Configuração para lojas com ponto compartilhado (ex: Loja e CD)."""
    nome_grupo: str
    lojas_membros: List[str]
    operacao: str = 'ATACADAO'
    ativo: bool = True


DEFAULT_SHARED_GROUPS: List[SharedStoreGroup] = [
    SharedStoreGroup(
        nome_grupo='ATACADAO TIJUCAL',
        lojas_membros=[
            'Vinicius - Atacadao Tijucal',
            'Vinicius - Atacadao CD Tijucal',
            'Atacadao Tijucal',
            'Atacadao CD Tijucal',
        ],
        operacao='ATACADAO',
        ativo=True,
    ),
    SharedStoreGroup(
        nome_grupo='ATACADAO TAGUATINGA',
        lojas_membros=[
            'Vinicius - Atacadao Taguatinga',
            'Vinicius - Atacadao Brasilia Taguatinga CD 8',
            'Vinicius - Sendas Taguatinga',
            'Atacadao Taguatinga',
            'Atacadao Brasilia Taguatinga CD 8',
            'Sendas Taguatinga',
        ],
        operacao='ATACADAO',
        ativo=True,
    ),
]

# Quadro padrão por loja para competências sem cadastro explícito no banco
DEFAULT_QUADROS: Dict[str, int] = {
    'ASSAI APARECIDA DE GOIANIA 348': 18,
    'ASSAI ARACATUBA 174': 14,
    'ASSAI ARICANDUVA 901': 30,
    'ASSAI BAURU 61': 16,
    'ASSAI ATACADISTA BOSQUE MAIA 258': 18,
    'ASSAI BRAS CUBAS 165': 14,
    'ASSAI BRASILIA SUL 51': 19,
    'ASSAI ACRISSUL 92': 16,
    'ASSAI CARAGUATATUBA 25': 12,
    'ASSAI CD ANHANGUERA 956': 23,
    'ASSAI CD CAJAMAR 915': 38,
    'ASSAI CEILANDIA 52': 15,
    'ASSAI CIDADE DUTRA 155': 17,
    'ASSAI COXIPO 57': 16,
    'ASSAI VARZEA GRANDE 70': 16,
    'ASSAI CURITIBA ALTO DO XV 259': 18,
    'ASSAI CURITIBA TREVO ATUBA 229': 12,
    'ASSAI CURITIBA JK 195': 14,
    'ASSAI CURITIBA KENNEDY 257': 15,
    'ASSAI CURITIBA 99': 16,
    'ASSAI FERNAO DIAS 89': 0,
    'ASSAI FOZ DO IGUACU 314': 15,
    'ASSAI FRANCO DA ROCHA 127': 17,
    'ASSAI GUAIANASES 60': 14,
    'ASSAI ITAQUAQUECETUBA 75': 14,
    'ASSAI SOROCABA ITAVUVU 50': 12,
    'ASSAI JACU PESSEGO 124': 19,
    'ASSAI JAGUARE 22': 11,
    'ASSAI JAGUARE III 273': 22,
    'ASSAI RIBEIRAO PRETO 63': 10,
    'ASSAI JOAO DIAS 18': 26,
    'ASSAI RIBEIRAO PRETO 14': 13,
    'ASSAI LONDRINA 71': 14,
    'ASSAI LONDRINA II 162': 13,
    'ASSAI MARINGA 79': 15,
    'ASSAÍ MINAS SHOPPING 283': 30,
    'ASSAI MOGI DAS CRUZES 81': 14,
    'ASSAI MOOCA 260': 28,
    'ASSAI PIRACICABA 167': 16,
    'ASSAI PIRACICABA 244': 16,
    'ASSAI DIADEMA PIRAPORINHA 156': 14,
    'ASSAI PRAIA GRANDE 104': 16,
    'ASSAI PRAIA GRANDE 59': 32,
    'ASSAI PRESIDENTE PRUDENTE 73': 13,
    'ASSAI RAPOSO TAVARES 270': 20,
    'ASSAI RIBEIRAO PRETO 240': 16,
    'ASSAI RIBEIRAO PRETO 301': 20,
    'ASSAI RONDONOPOLIS FLORESTA 216': 16,
    'ASSAI SANTA BARBARA D OESTE 237': 15,
    'ASSAI SANTA ROSA 329': 24,
    'ASSAI SANTOS 7': 11,
    'ASSAI SANTOS ANA COSTA 313': 39,
    'ASSAI SAO JOSE DOS CAMPOS 121': 14,
    'ASSAI SAO JOSE DOS CAMPOS PASSARO MARROM 354': 18,
    'ASSAI SINOP 180': 17,
    'ASSAI SUZANO 68': 14,
    'ASSAI TABOAO DA SERRA 112': 13,
    'ASSAI TAGUATINGA 101': 18,
    'ASSAI PENHA TIQUATIRA 275': 23,
    'ASSAI UBERLANDIA 158': 26,
    'ASSAI VALPARAISO 117': 16,
    'ATACADAO ANCHIETA 269': 14,
    'ATACADAO APARECIDA DE GOIANIA 935': 13,
    'ATACADAO APARECIDA DE GOIANIA II 931': 9,
    'ATACADAO ARACATUBA 648': 8,
    'ATACADAO ARARAQUARA 738': 13,
    'ATACADAO ASA NORTE 61': 15,
    'ATACADAO BAURU 139': 14,
    'ATACADAO BIGUACU 314': 7,
    'ATACADAO BRASILIA NORTE 295': 12,
    'ATACADAO CACHOEIRINHA 740': 10,
    'ATACADAO CAMBE 258': 8,
    'ATACADAO CAMBUCI 680': 16,
    'ATACADAO CAMPINAS DUNLOP 677': 13,
    'ATACADAO CAXIAS DO SUL 284': 10,
    'ATACADAO APARECIDA DE GOIANIA CD 232': 6,
    'ATACADAO CD MATRIZ 111 111': 19,
    'ATACADAO BRASILIA TAGUATINGA CD 8': 3,
    'ATACADAO CD TIJUCAL 802': 6,
    'ATACADAO CAMPO GRANDE CENTENARIO 355': 13,
    'ATACADAO CUIABA CHAPADA 890': 15,
    'ATACADAO CAMPO GRANDE AT 2': 7,
    'ATACADAO CAMPO GRANDE ANTONINO AS 3': 16,
    'ATACADAO CAMPO GRANDE COSTA E SILVA 31': 16,
    'ATACADAO COTIA RAPOSO 652': 15,
    'ATACADAO CUIABA II 889': 15,
    'ATACADAO DIADEMA CUPECE 640': 19,
    'ATACADAO DIADEMA SERRARIA 675': 10,
    'ATACADAO DOURADOS 7': 16,
    'ATACADAO CAMPO GRANDE DUQUE 137': 16,
    'ATACADAO EDUCANDARIO 303': 9,
    'ATACADAO FLORIANOPOLIS 290': 9,
    'ATACADAO FORMOSA 901': 9,
    'ATACADAO FRANCA 685': 15,
    'ATACADAO GAMA 297': 11,
    'ATACADAO GOIANIA PERIMETRAL 930': 8,
    'ATACADAO GOIANIA FLAMBOYANT 717': 11,
    'ATACADAO GURUPI 673': 9,
    'ATACADAO PORTO ALEGRE HUMAITA 847': 8,
    'ATACADAO INAJAR DE SOUZA 251': 13,
    'ATACADAO INDAIATUBA 658': 9,
    'ATACADAO IPIRANGA 133': 15,
    'ATACADAO ITAPECERICA 941': 16,
    'ATACADAO ITAQUAQUECETUBA 627': 13,
    'ATACADAO ITAQUERA 48': 17,
    'ATACADAO ITUMBIARA 904': 13,
    'ATACADAO JACAREI 814': 9,
    'ATACADAO VILA JACUI 120': 16,
    'ATACADAO JOINVILLE 282': 7,
    'ATACADAO JUIZ DE FORA 147': 12,
    'ATACADAO LIMEIRA 614': 13,
    'ATACADAO LIMEIRA CENTRO 621': 0,
    'ATACADAO MARILIA 630': 14,
    'ATACADAO MATRIZ 1': 24,
    'ATACADAO MAUA 631': 15,
    'ATACADAO OURINHOS 643': 12,
    'ATACADAO PALMAS 671': 0,
    'ATACADAO PARELHEIROS 57': 16,
    'ATACADAO PATOS DE MINAS 712': 8,
    'ATACADAO PENHA 937': 18,
    'ATACADAO PIRACICABA 946': 15,
    'ATACADAO PIRITUBA 938': 16,
    'ATACADAO POA 656': 14,
    'ATACADAO CUIABA PORTO 928': 16,
    'ATACADAO PORTO CEASA 288': 10,
    'ATACADAO PRAIA GRANDE 731': 17,
    'ATACADAO RECANTO DAS EMAS 320': 10,
    'ATACADAO RIBEIRAO PIRES 678': 13,
    'ATACADAO RIO VERDE 922': 11,
    'ATACADAO RONDONOPOLIS 886': 16,
    'ATACADAO SANTA BARBARA D OESTE 948': 13,
    'ATACADAO SANTO AMARO 20': 17,
    'ATACADAO SANTO ANDRE 615': 14,
    'ATACADAO SANTOS 46': 15,
    'ATACADAO SANTOS PORTO 365': 2,
    'ATACADAO SAO BERNARDO DEMARCHI 659': 13,
    'ATACADAO SAO BERNARDO DO CAMPO 943': 16,
    'ATACADAO SAO BERNARD 714': 17,
    'ATACADAO SAO CAETANO 639': 14,
    'ATACADAO SAO CARLOS 735': 13,
    'ATACADAO SAO JOSE DOS CAMPOS 737': 17,
    'ATACADAO SAO JOSE DOS CAMPOS 744': 13,
    'ATACADAO SAO JOSE DOS CAMPOS SHOPPING 813': 8,
    'ATACADAO SAO LEOPOLDO 283': 9,
    'ATACADAO SAO MIGUEL 35': 17,
    'ATACADAO PORTO ALEGRE SARANDI 867': 4,
    'ATACADAO SOBRADINHO 350': 9,
    'ATACADAO SOROCABA 657': 14,
    'ATACADAO SUMARE 736': 12,
    'ATACADAO SUPECO SOROCABA 647': 4,
    'ATACADAO SUZANO 732': 16,
    'ATACADAO TABOAO DA SERRA 634': 14,
    'ATACADAO TAGUATINGA 343': 11,
    'ATACADAO BRASILIA TAGUATINGA 14': 15,
    'ATACADAO TATUAPE 340': 18,
    'ATACADAO TAUBATE 653': 14,
    'ATACADAO TIJUCAL 927': 16,
    'ATACADAO TRES LAGOAS 237': 14,
    'ATACADAO UBERABA 241': 10,
    'ATACADAO UBERLANDIA 30': 12,
    'ATACADAO VALPARAISO 900': 13,
    'ATACADAO VILA GUILHERME 4671': 17,
    'ATACADAO VILA MARIA 60': 17,
    'ASSAI VILA SONIA 08': 10,
    'ASSAI OSASCO AUTONOMISTAS CENTRO 357': 18,
    'ATACADAO ADM TATUAPE 338': 16,
    'ATACADAO CARAGUATATUBA': 15,
}
