# Generated by Django 5.2.14 on 2026-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0035_headcountmensalloja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='dispensa_gestao_pessoas',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='headcount_real',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='nome_gestao',
        ),
        migrations.AddField(
            model_name='loja',
            name='dispensa_divergencia_ponto',
            field=models.BooleanField(default=False, help_text='Marque quando a loja for administrativa ou de apoio volante para não acusar divergência com o ponto físico da GeoVictoria.', verbose_name='Dispensa Divergência Ponto (GeoVictoria)'),
        ),
    ]
