# Generated by Django 5.2.14 on 2026-09-28 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0036_remove_loja_dispensa_gestao_pessoas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escopomensal',
            name='dsr_valor_fixo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo orçado para DSR variável no escopo deste mês.', max_digits=12, verbose_name='DSR Variável Fixo (R$)'),
        ),
    ]
