# Generated by Django 5.2.14 on 2026-09-28 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0037_escopomensal_dsr_valor_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemescopomensal',
            name='dsr_valor_fixo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo orçado para DSR variável deste cargo no mês.', max_digits=12, verbose_name='DSR Variável Fixo (R$)'),
        ),
    ]
